name: Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
        java-version: [11]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'adopt'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        ./scripts/test_runner.py --category unit

    - name: Run integration tests
      run: |
        ./scripts/test_runner.py --category integration

    - name: Run performance tests
      run: |
        ./scripts/performance_tester.py --type load --users 10

    - name: Generate test reports
      run: |
        ./scripts/test_analyzer.py --analyze-all latest

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: sample_analysis_results/*/reports/

    - name: Check test coverage
      run: |
        coverage run -m pytest
        coverage report
        coverage html

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: htmlcov/
