# Test Workflow Configuration

# Test execution settings
execution:
  parallel: true
  max_workers: 4
  timeout: 300  # seconds
  retry:
    enabled: true
    max_attempts: 3
    backoff: 5  # seconds

# Test categories and priorities
categories:
  unit:
    priority: high
    parallel: true
    timeout: 60
    required: true
    
  integration:
    priority: medium
    parallel: false
    timeout: 120
    required: true
    
  performance:
    priority: low
    parallel: false
    timeout: 300
    required: false

# Test data management
test_data:
  datasets:
    small:
      size: 15
      valid_ratio: 0.67
      
    medium:
      size: 150
      valid_ratio: 0.67
      
    large:
      size: 1500
      valid_ratio: 0.67
      
    performance:
      size: 10000
      valid_ratio: 0.5

# Test environment
environment:
  setup:
    - clean_workspace
    - init_database
    - load_test_data
    
  teardown:
    - cleanup_data
    - reset_state
    - archive_results

# Reporting configuration
reporting:
  formats:
    - html
    - json
    - md
    
  metrics:
    - response_time
    - success_rate
    - coverage
    - memory_usage
    
  visualizations:
    - response_time_dist
    - error_rates
    - performance_trends

# Monitoring settings
monitoring:
  enabled: true
  interval: 60  # seconds
  metrics:
    - cpu
    - memory
    - disk
    - network

# CI/CD integration
ci_cd:
  triggers:
    - push
    - pull_request
    - schedule
    
  branches:
    - main
    - develop
    - feature/*
    
  notifications:
    on_failure:
      - email
      - slack
    on_success:
      - slack

# Schedule configuration
schedule:
  unit_tests:
    frequency: commit
    timeout: 300
    
  integration_tests:
    frequency: daily
    time: "00:00"
    
  performance_tests:
    frequency: weekly
    day: sunday
    time: "02:00"

# Resource limits
resources:
  cpu:
    limit: 4
    request: 2
    
  memory:
    limit: "4Gi"
    request: "2Gi"
    
  storage:
    limit: "10Gi"
    request: "5Gi"

# Cleanup policies
cleanup:
  test_results:
    enabled: true
    retention_days: 30
    
  test_data:
    enabled: true
    retention_days: 7
    
  logs:
    enabled: true
    retention_days: 14
